### ISSUE TITLE
Getting a 404 error when clicking on the main repo link

### ISSUE THREAD

**Issue by mukeshthawani** [fastlane/frameit-frames#1]
I think the URL for main repo is [https://github.com/fastlane/fastlane/tree/master/frameit](). Let me know if I am correct I will create a PR for that.

**Comment by mfurtak** [comment]
Hi @mukeshthawani - this project is under rapid development, so we may be in a temporarily incorrect state. Please give us a day or so to wrap things up, and then if it still looks wrong, please do submit a PR! 👍

**Comment by KrauseFx** [comment]
Thanks @mukeshthawani, that's correct, the link will work once https://github.com/fastlane/fastlane/pull/6597 is merged 👍

**Comment by mukeshthawani** [comment]
Ok. Thanks for the update @KrauseFx
