### ISSUE TITLE
download templates timeout issues

### ISSUE THREAD

**Issue by hite** [fastlane/frameit-frames#2]
the first time  I run 
```
fastlane frame
```
I got error.
>INFO [2017-04-17 20:43:46.72]: Downloading file from 'https://fastlane.github.io/frameit-frames/1478730760/files.json' ...
INFO [2017-04-17 20:43:51.86]: Downloading 1 of 41 files from 'https://fastlane.github.io/frameit-frames/1478730760/Apple%20iPhone%205c%20Blue.png' ...
ERROR [2017-04-17 20:44:04.82]: Operation timed out - connect(2) for 151.101.88.133:443 (Errno::ETIMEDOUT)
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.27.0/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Error accessing URL 'https://fastlane.github.io/frameit-frames/1478730760/Apple%20iPhone%205c%20Blue.png' (FastlaneCore::Interface::FastlaneError)

It aborted to continue .But I typed `https://fastlane.github.io/frameit-frames/1478730760/Apple%20iPhone%205c%20Blue.png` into Chrome, it can be downloaded.

So I downloaded zip of repository, and put it into '/Users/hite/.fastlane/frameit/' , run `fastlane frameit`.
The problem was solved.

So any suggests?

**Comment by hite** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.27.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.3      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.4        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-04-17**
</details>

**Comment by janpio** [comment]
Sounds like a temporary problem on GitHub's side or a general connection problem between you and GitHub.
